### ISSUE TITLE
Change expand animation to Googles guideline example

### ISSUE THREAD

**Issue by G00fY2** [jahirfiquitiva/FABsMenu#19]
Would be nice if we could get the animation from Googles expandable FAB in the material guidelines: [A floating action button flinging out related actions](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B8v7jImPsDi-Znh2YWx1VnE3NEk/components-buttons-fab-transition-speeddial-01.mp4)

If I find some time I try to adapt this animation and make a PR.

**Comment by jahirfiquitiva** [comment]
Unfortunately, due to my limited time between work+University, I don't really find the way to provide proper support for this library. I really appreciate everyone that has been using it and that might continue using it, but, at least for now, this library is deprecated.

If you want to use a similar and more frequently updated library, please refer to @leinardi 's [FloatingActionSpeedDial](https://github.com/leinardi/FloatingActionButtonSpeedDial)

Thanks again for the amazing support. :raised_hands:
